name: Deploy doghouse
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 50 # Need git history for testing.
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          # must sync doghouse/appengine/app.yaml
          go-version: "1.24"
      - run: go test -v -race  ./...
  deploy:
    permissions:
      contents: read
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./doghouse/appengine/
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: auth
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.12
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@cb1e50a9932213ecece00a606661ae9ca44f3397 # v2.2.0
        with:
          project_id: review-dog
      - name: Decrypt keys
        env:
          GAE_KEYRING_NAME: reviewdog-doghouse-deploy
          GAE_KEY_NAME: secret-env
        run: |-
          gcloud kms decrypt --location=global \
            --keyring="$GAE_KEYRING_NAME" \
            --key="$GAE_KEY_NAME" \
            --ciphertext-file=secret/encrypted-reviewdog.private-key.pem.bin \
            --plaintext-file=secret/reviewdog.private-key.pem
          gcloud kms decrypt --location=global \
            --keyring="$GAE_KEYRING_NAME" \
            --key="$GAE_KEY_NAME" \
            --ciphertext-file=secret/encrypted-secret.yaml.bin \
            --plaintext-file=secret/secret.yaml
      - name: Deploy
        run: gcloud --quiet app deploy app.yaml
      - name: Cleanup
        run: |-
          rm secret/reviewdog.private-key.pem
          rm secret/secret.yaml
