name: Proto
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Built
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Build
      working-directory: proto/
      run: ./update.sh
    - name: Check diff
      run: git diff --exit-code
