name: release test
on:
  push:
    branches:
      - master
      - release-*
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - .github/workflows/release_test.yml
      - ".goreleaser*.yml"
      - go.mod
      - go.sum

jobs:
  release_test:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Setup Go for building reviewdog binary.
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "go.mod"

      - name: Test goreleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          version: "~> v2"
          args: check
