name: release test
on:
  push:
    branches:
      - master
      - release-*
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - .github/workflows/release_test.yml
      - ".goreleaser*.yml"
      - go.mod
      - go.sum

jobs:
  release_test:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Setup Go for building reviewdog binary.
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: "go.mod"

      - name: Test goreleaser
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
        with:
          version: "~> v2"
          args: check
